import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { buildCatalog } from "../src/seed-data/catalog.js";
import { LYRIC_MAP } from "../src/seed-data/lyric-map.js";
import { VERSE_EXPANSION as PRIOR } from "../src/seed-data/verse-expansion.js";

// Emits src/seed-data/verse-expansion.ts: title → stanzas present in the song's
// word-timing JSON (tools/seed-assets/lyrics/) but missing from its seed chordPro.
// Fixes the original seed batches (hymns.ts, hymns2.ts) that only carried Verse 1.
// ponytail: appended stanzas are chordless — every verse shares the tune, and naive
// chord copying misplaces syllable-level chords; align from ABC if chords matter.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

const stanzaLabels = (chordPro: string) =>
  new Set(chordPro.split(/\r?\n\s*\r?\n/).map(b => b.split(/\r?\n/)[0].trim()).filter(Boolean));

const { rows } = buildCatalog("");
const expansion: Record<string, string> = {};
let skipped = 0;

for (const row of rows) {
  const lyr = LYRIC_MAP[row.title];
  if (!lyr) { skipped++; continue; }
  const timing = JSON.parse(fs.readFileSync(path.join(__dirname, "seed-assets", "lyrics", lyr.file), "utf8"));
  // catalog.ts already appends the current expansion — strip it so reruns are idempotent
  const base = PRIOR[row.title] ? row.chordPro.replace("\n\n" + PRIOR[row.title], "") : row.chordPro;
  const have = stanzaLabels(base);
  const missing = timing.stanzas.filter((s: any) => !have.has(s.label));
  if (missing.length === 0) continue;
  expansion[row.title] = missing
    .map((s: any) => s.label + "\n" + s.lines.map((l: any[]) => l.map(w => w.text).join(" ")).join("\n"))
    .join("\n\n");
}

const out =
  "// Generated by tools/backfill-verses.ts — stanzas beyond the seed chordPro,\n" +
  "// taken from the word-timing JSONs in tools/seed-assets/lyrics/. Do not edit by hand.\n" +
  "export const VERSE_EXPANSION: Record<string, string> = {\n" +
  Object.entries(expansion).map(([t, v]) => `  ${JSON.stringify(t)}: ${JSON.stringify(v)}`).join(",\n") +
  "\n};\n";
fs.writeFileSync(path.join(ROOT, "src", "seed-data", "verse-expansion.ts"), out);
console.log(`verse-expansion.ts: ${Object.keys(expansion).length} songs expanded, ${skipped} without timing files.`);
