import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { buildCatalog } from "../src/seed-data/catalog.js";
import { MIDI_MAP_HYMNSITE } from "../src/seed-data/midi-map-hymnsite.js";

// Fetches melody MIDIs from HymnSite.com for catalog songs the Open Hymnal import
// didn't cover: tsx tools/import-hymnsite.ts
// Legal basis: HymnSite's FAQ places its umh###.mid files under no restrictions at
// all ("You want to package them up and sell them? Go ahead. Really--NO RESTRICTIONS."
// — hymnsite.com/faq.htm). Only umh-prefixed files are used.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const assetDir = path.join(__dirname, "seed-assets", "midi");
const norm = (s: string) => s.toLowerCase().replace(/['’,!()."]/g, "").replace(/[^a-z0-9]+/g, " ").trim();

const indexHtml = await (await fetch("https://www.hymnsite.com/abc.sht")).text();
const index = new Map<string, string>();
for (const m of indexHtml.matchAll(/href="\/lyrics\/(umh\d+)\.sht"[^>]*>([^<]+)</gi)) {
  const title = norm(m[2].replace(/\(\d+\)\s*$/, ""));
  if (!index.has(title)) index.set(title, m[1]);
}

// Same hymn, different title on HymnSite — verified by hand, not fuzzy-matched.
const ALIASES: Record<string, string> = {
  "battle hymn of the republic": "the battle hymn of the republic",
  "here o my lord i see thee face to face": "here o my lord i see thee",
  "the strife is oer": "the strife is oer the battle done",
  "were marching to zion": "marching to zion",
  "on jordans stormy banks": "on jordans stormy banks i stand",
};

const { rows } = buildCatalog("");
const candidates = rows.filter((r: any) => !r.midiUrl && r.license === "PD");
const hits: [string, string][] = [];
for (const r of candidates) {
  const n = norm(r.title);
  const u = index.get(n) || index.get(ALIASES[n] ?? "") || index.get(n.replace(/^o /, "oh ")) || index.get(n.replace(/^oh /, "o "))
    || index.get(n.replace(/\bye\b/, "you")) || index.get(n.replace(/\byou\b/, "ye"));
  if (u) hits.push([r.title, u]);
}
console.log(`HymnSite index: ${index.size} hymns; matched ${hits.length} of ${candidates.length} catalog songs still lacking a MIDI`);

fs.mkdirSync(assetDir, { recursive: true });
const bytes: Record<string, number> = {};
for (const [title, umh] of hits) {
  const file = `${umh}.mid`;
  const target = path.join(assetDir, file);
  if (!fs.existsSync(target)) {
    const resp = await fetch(`https://www.hymnsite.com/midifiles/${file}`);
    if (!resp.ok) { console.error(`  skip ${title}: HTTP ${resp.status}`); continue; }
    fs.writeFileSync(target, Buffer.from(await resp.arrayBuffer()));
    await new Promise(r => setTimeout(r, 300));
  }
  bytes[title] = fs.statSync(target).size;
  console.log(`  ${umh} <- ${title}`);
}

const merged: Record<string, { file: string; bytes: number }> = { ...MIDI_MAP_HYMNSITE };
hits.filter(([t]) => bytes[t] !== undefined).forEach(([t, u]) => { merged[t] = { file: u + ".mid", bytes: bytes[t] }; });
const lines = Object.entries(merged).sort(([a], [b]) => a.localeCompare(b))
  .map(([t, m]) => `  ${JSON.stringify(t)}: { file: ${JSON.stringify(m.file)}, bytes: ${m.bytes} }`);
fs.writeFileSync(path.join(__dirname, "..", "src", "seed-data", "midi-map-hymnsite.ts"),
  `// Generated by tools/import-hymnsite.ts — do not edit by hand.
// Melody MIDI files from HymnSite.com's umh### collection, which its FAQ
// releases with no restrictions (hymnsite.com/faq.htm).
export const MIDI_MAP_HYMNSITE: Record<string, { file: string; bytes: number }> = {
${lines.join(",\n")}
};
`);
console.log(`Wrote midi-map-hymnsite.ts (${lines.length} songs)`);
const { execSync } = await import("child_process");
execSync("npx eslint --fix src/seed-data/midi-map-hymnsite.ts", { cwd: path.join(__dirname, ".."), stdio: "inherit" });
