import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { buildCatalog } from "../src/seed-data/catalog.js";

// Picks one YouTube performance per catalog song: takes the top search result whose
// title actually matches the song, then verifies it exists and allows embedding via
// oEmbed. Legal basis: videos are embedded via YouTube's standard iframe embeds —
// hosting and rights stay with YouTube and the uploader. Review the report file
// (tools/video-report.txt) after each run.
// Usage: tsx tools/import-videos.ts
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
// YouTube throttles bursts hard — space requests out and back off on connection resets
const fetchRetry = async (url: string, opts: any) => {
  for (let attempt = 0; ; attempt++) {
    try {
      const resp = await fetch(url, opts);
      if (resp.status !== 429) return resp;
      throw new Error("HTTP 429");
    } catch (e) {
      if (attempt >= 3) throw e;
      await sleep(15000 * (attempt + 1));
    }
  }
};
const norm = (s: string) => s.toLowerCase().replace(/&#?\w+;/g, " ").replace(/['’,!()."]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const STOP = new Set([
  "a", "an", "the", "of", "in", "to", "and", "is", "o", "oh", "for", "my", "thy", "with"
]);

function candidates(html: string): { id: string; title: string }[] {
  const out: { id: string; title: string }[] = [];
  const seen = new Set<string>();
  for (const m of html.matchAll(/"videoRenderer":\{"videoId":"([\w-]{11})"/g)) {
    if (seen.has(m[1])) continue;
    seen.add(m[1]);
    const slice = html.slice(m.index, (m.index || 0) + 3000);
    const t = slice.match(/"title":\{"runs":\[\{"text":"((?:[^"\\]|\\.)*)"/);
    if (t) out.push({ id: m[1], title: JSON.parse(`"${t[1]}"`) });
    if (out.length >= 10) break;
  }
  return out;
}

async function pick(songTitle: string): Promise<{ id: string; videoTitle: string } | null> {
  const q = encodeURIComponent(`"${songTitle}" hymn`);
  const resp = await fetchRetry(`https://www.youtube.com/results?search_query=${q}&sp=EgIQAQ%253D%253D`, { headers: { "user-agent": UA, cookie: "CONSENT=YES+1" } });
  if (!resp.ok) throw new Error(`search HTTP ${resp.status}`);
  const html = await resp.text();

  const words = norm(songTitle).split(" ").filter(w => w && !STOP.has(w));
  for (const c of candidates(html)) {
    const vt = norm(c.title);
    const matched = words.filter(w => vt.includes(w)).length;
    if (matched < Math.ceil(words.length * 0.8)) continue;
    const oe = await fetchRetry(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${c.id}&format=json`, { headers: { "user-agent": UA } });
    if (!oe.ok) continue; // 401/404 → embedding disabled or gone
    return { id: c.id, videoTitle: c.title };
  }
  return null;
}

const { rows } = buildCatalog("");
const map: Record<string, { id: string; videoTitle: string }> = {};
const report: string[] = [];
for (const r of rows) {
  try {
    const found = await pick(r.title);
    if (found) {
      map[r.title] = found;
      report.push(`${r.title}  ->  ${found.videoTitle}  (youtu.be/${found.id})`);
      console.log(`  ok ${r.title} -> ${found.videoTitle}`);
    } else {
      report.push(`${r.title}  ->  (no confident match)`);
      console.log(`  -- ${r.title}`);
    }
  } catch (e: any) {
    report.push(`${r.title}  ->  ERROR ${e.message}`);
    console.log(`  !! ${r.title}: ${e.message}`);
  }
  await sleep(2500);
}

const lines = Object.entries(map).sort(([a], [b]) => a.localeCompare(b))
  .map(([t, v]) => `  ${JSON.stringify(t)}: { id: ${JSON.stringify(v.id)}, videoTitle: ${JSON.stringify(v.videoTitle)} }`);
fs.writeFileSync(path.join(__dirname, "..", "src", "seed-data", "video-map.ts"),
  `// Generated by tools/import-videos.ts — do not edit by hand.
// One curated YouTube performance per song, verified live via oEmbed at import time.
export interface VideoInfo { id: string; videoTitle: string; }
export const VIDEO_MAP: Record<string, VideoInfo> = {
${lines.join(",\n")}
};
`);
fs.writeFileSync(path.join(__dirname, "video-report.txt"), report.join("\n") + "\n");
console.log(`Wrote video-map.ts (${lines.length} of ${rows.length} songs) + tools/video-report.txt`);
const { execSync } = await import("child_process");
execSync("npx eslint --fix src/seed-data/video-map.ts", { cwd: path.join(__dirname, ".."), stdio: "inherit" });
