import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

// Rewrites src/seed-data/art-map.ts from whatever is sitting in tools/seed-assets/cover-art,
// matching a file to a song when its name is the song title slugified (same slug rule as the
// writer portraits). Drop <song-title-slug>.webp in that folder and run this — yarn seed does
// it for you. The map is checked in because prod migrations run in the VPC Lambda, which
// doesn't ship the asset folder.
// Usage: tsx tools/sync-cover-art.ts
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ART_DIR = path.join(__dirname, "seed-assets", "cover-art");
const OUT = path.join(__dirname, "..", "src", "seed-data", "art-map.ts");

// apostrophes vanish rather than splitting a word — "David's" is davids, not david-s
export const slugFor = (name: string) =>
  name.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const write = (entries: [string, string][]) => fs.writeFileSync(OUT,
  `// Generated by tools/sync-cover-art.ts — do not edit by hand.\n` +
  `// Song hero art, keyed by title like the midi/lyric maps. Files live in\n` +
  `// tools/seed-assets/cover-art and are served as songs/<songId>/art.webp.\n` +
  `export const ART_MAP: Record<string, { file: string }> = {\n` +
  entries.map(([title, file]) => `  ${JSON.stringify(title)}: { file: ${JSON.stringify(file)} }`).join(",\n") +
  `\n};\n`);

export async function syncCoverArt(): Promise<string[]> {
  if (!fs.existsSync(OUT)) write([]);  // catalog.ts imports the map, so it must exist before we load it
  const { buildCatalog } = await import("../src/seed-data/catalog.js");
  const titles = buildCatalog("").rows.map(r => r.title as string);

  const files = new Set(fs.readdirSync(ART_DIR).filter(f => f.endsWith(".webp")));
  const entries: [string, string][] = [];
  for (const title of titles) {
    const file = `${slugFor(title)}.webp`;
    if (files.delete(file)) entries.push([title, file]);
  }
  write(entries.sort((a, b) => a[0].localeCompare(b[0])));
  return [...files];  // leftovers match no song — the caller warns about them
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const orphans = await syncCoverArt();
  console.log(`Synced src/seed-data/art-map.ts${orphans.length ? ` — no song matches: ${orphans.join(", ")}` : ""}`);
}
